ALL_ALCHEMY = [
"#default",
"Synth Bass Perfection",
"Solid Bass",
"Smooth Jazz",
"Lazarus",
"Resistance Synth",
"Rhombus",
"Operator Two",
"Choom Bass",
"Overblown Deep Bass",
"Short Deep Bass",
"Analog Sustained Virtually",
"Whopper",
"Cycling Space Bass",
"Deep Atmospheric",
"Amped Peak",
"Ball Bass",
"Short Wobble Bass",
"Eastern Stack",
"Juicy Bass Stack",
"Dark And Deep Bass",
"Solar Eclipse",
"Rounded Bass",
"Massive Analog Funk Bass",
"Post-Modern Synth Bass",
"Journey Home",
"Punchy Short Bass",
"Battle Bass",
"Sine Drive",
"Gothic Sweeper",
"Swamp",
"Treated Upright",
"Planet Dada",
"Belly Button",
"Super Saw Festival Synth",
"Dub Bass",
"Dark Drive Stack",
"Tau Hollows Bass",
"Invader",
"Day Glow Bass",
"Bottom Feeder",
"This Is Drum and Bass",
"Ghostly Bandura Bass",
"Face Plant",
"Lazy Pinch",
"Random Filter Bass",
"Cutting Bass",
"Ignition Bass",
"Short Buzz Bass",
"80s Disco Funk",
"Perry Bass",
"Slow Acid Wave Bass",
"Cutter",
"Formant Bass",
"Groovy Synth Pattern 02",
"Driving Glide Pattern",
"Silencio",
"Quirky Chaos",
"Bell Modulus",
"Long Run",
"Ceremony Sanctuary",
"Resonant Confusion",
"Chaotic Filter Lead",
"Rhythmic Gate",
"Arpeggio Song",
"Canadian Crush",
"Indonesia Loop",
"Glitchy Clicks",
"Special Fader",
"Massiveness",
"Expanding Nebula",
"Mega Strings",
"Platinum Motion",
"Vocoder Pad",
"Brassy Jazz Ensemble",
"Additive Sustain",
"Crossing the Universe",
"Horizon Strings Sweep",
"Layers of Silver",
"Directionless Layers",
"Nocturne",
"Moment of Insight",
"Amber Dark",
"Daybreak Horizon",
"Glass Space",
"Step Sequence 2",
"Brassy and Funky",
"Rich String Pad",
"Perfect Pad 01",
"Glass Xylophone Stack",
"Choir Mmm",
"From The Deep",
"Liquid Sun",
"Lunar Orbit",
"Analog Poly Ensemble",
"Galactic Choir",
"Step Sequence 3",
"Sitar Drones",
"Step Sequence 1",
"Bell String Pad",
"Perfect Pad 02",
"Waveform Reunion",
"Clouds Set Adrift",
"Jupiter Orbit Strings",
"Dynamic String Layer",
"Choir Oooh",
"Mega Vintage",
"Saragossa Sea",
"Perfect Pad 03",
"Epic Synth String Ensemble",
"Brassy Analog Sweep",
"Smooth FM",
"Lush Multi Layer 2",
"Vintage Brassy Sweep",
"Sweet Pop",
"Glitter Club",
"Choir Mist",
"Starship Infinity",
"80s Air Pad",
"Choir Ahh",
"Outback Sunset",
"Lush Multi Layer 1",
"Dark Veil",
"Analog Sweep",
"Voices Of The Veil",
"Organic Motion Pad",
"Diffused Emotion",
"Dark Ensemble",
"Alpha Pad",
"Sea Of Possibilities",
"Riding the Sunset Wave",
"Majestic Swells",
"Frozen Choir Sweep",
"Kingdom Of The Sun",
"Granular Diffusion 1",
"Dark and Distant",
"Trance Multi-Point",
"Wide Saw Pad",
"Granular Strings",
"Classic Sweep 2",
"Angels Falling",
"Evolving Space 1",
"Bright Shimmer Sweep",
"Triumphant Swirling Pad",
"Cold Emotion Sweep",
"Sweeping The Stratosphere",
"Soft and Dark",
"Classic Sweep 1",
"Odd Vox Pad",
"Synth Vox",
"Star Voice Control",
"Alone",
"Distant Sweep Space",
"1980 Sweet Pad",
"Trance Breakdown",
"Vintage String 2",
"Strings Dark Purple",
"Angelic Waves",
"Glacier Reflections",
"Analog Smooth",
"Electro Sweeper",
"Vintage String 1",
"Hall Of the Stone Church",
"Motion Glory Wave",
"Journey Thru Space",
"Vintage Dust Strings",
"Heavens Sweep",
"Husky Grain Vox",
"Choir Synth",
"Dust World Sweep",
"Atmospheric Phenomenon",
"Long Winter Sustain",
"High Pass Clouds",
"Waves Of Liquid Glass",
"Suspended Choir",
"Pad Machine",
"Synth Voice",
"Monster Bottom End",
"Ice Air",
"Galactic Starfield",
"Deep Space Choir",
"Awaken From A Dream",
"Winter Cold Sweep",
"Wave Sequence 2",
"Endless Sky",
"Old Choir Tapes",
"Gliding Descent",
"Vintage Synth Dual Sweep",
"Wave Sequence 1",
"Cinematique",
"The Neverending Universe",
"Metallic Sweeps",
"Slowly Undulating Pad",
"Cream Unison",
"Deep Voices Of The Veil",
"Reef Glow",
"Dreamtime Traveler",
"Air Choir Sweep",
"Sweep Shuffle",
"Angelic Motion",
"Cosmic Hum Sweep",
"Spectral Waves",
"Steps In Space",
"Waves of Synth Pads",
"Poly Synth Dream",
"Luminous Pad",
"Empire Strings Space",
"Cascading Sweep",
"Deeper Emotion",
"Vintage Silk Motion",
"Above The Clouds",
"Vintage Warmer",
"Vintage String Machine",
"Evolving Organic Drama",
"Rising Tides",
"Midnight In Additive Land",
"Slow Morph Evolution",
"Warm Body",
"Granular India",
"Crystal Drop",
"Cosmic Teardrops",
"Bridled",
"Milky Teardrops",
"Dub Brass",
"Fast Vox",
"Chuck",
"Falling Stars",
"Viral Organ",
"Liquor Fumes",
"Punchy Drama",
"Old School Keys",
"Bell Driver",
"Fluffy Glitter",
"Amped Up Epic Synth",
"Chirping",
"Cheesy Decays",
"Orientation",
"Highlands",
"Saturated Dreams",
"Glass Piano Pad Stack",
"Chattering Bell Pad",
"Lonely Grains",
"Criminal Justice",
"Sundays",
"Gentle Bell Waves",
"Breathing",
"Brain Drain",
"Pulsar",
"Heavenly Teardrops",
"Analogy",
"Resonant Synth Bass",
"Vox Lead",
"Arcturus",
"Elements",
"Scarlet",
"Pulsing Dream Pad",
"Ultimate 90s",
"Soft Chords",
"Backwards Masking",
"Plucked Ghosts",
"Old School Keyboard",
"Vibrating Saw Piano",
"Open The Bottle",
"Bit Bells",
"Living Room",
"Deep Plucked Synth",
"Short Percussive Synth",
"Serpentine Wobble Bass",
"Decays",
"Paris",
"Kick Boxer",
"Poly Fissure",
"Dark Bellphone",
"Kaleidoscope Stab",
"Zeal",
"Tight Plucks",
"Wide Swirling Pad",
"Dusty Metal",
"Shadow Rose",
"90s Drama Keys",
"Bright Swelling Synth",
"Bell Designer",
"Fly-By-Night Lead",
"Synth Chime Echoes",
"Liquid Crystal",
"Flutters",
"Old Time",
"Melodic Sequencer",
"Solid Synth Keys",
"Classic Simple Synth 01",
"Axiom Escort",
"Stocked",
"Soft Bell Chords",
"Classic Simple Synth 02",
"Dreamy Plucks",
"Spiritual Downpour",
"Fantasy Keys",
"Stringed Thing Perhaps",
"Rising Bubbles",
"Falling Bells",
"Artificial Nectar",
"Beautiful Ambient Bells",
"Moon Bells",
"Copenhagen",
"Back Stab",
"Low Shuffler",
"Groovy Synth Pattern 01",
"Kneeling Arp",
"Bright Arpeggiated Synth",
"Capricorn",
"Perfect Fit Synth Patterns",
"Foreign Relations",
"Different Stages",
"Mixed Soft Heaven Strings",
"Hammered",
"The Worm",
"Catch It",
"Drifting Images",
"Chasseur",
"Getting The Jitters",
"Berlin Psychedelic",
"Cycling Bells",
"Noisy Definition",
"Bright Synth Patterns",
"70s Rock Synth Patterns",
"Night Magic",
"Childish Movement",
"Morph Me",
"Initial Adventure",
"Random Synth Bells",
"Lifter",
"Rise And Fall Patterns",
"Arps With Hats",
"Comb Groover",
"Morning Prayer",
"Exit The Void",
"Humpback Guitar",
"Earthworm",
"Chelonian Sequence",
"Sleep",
"Berlin Modular2",
"Hypnotic",
"Manic Mallet Arp",
"Hybrid Dancer",
"Heavy Water",
"Morphing Toy Bell",
"Berlin Spy",
"Around You Arp",
"Plucked Synth Strings",
"Saturated Groove",
"Synth Vox Patterns",
"Tough Driving Arpeggiator",
"Progressive House Pluck",
"Techno Chord Sequences",
"Juicy Arp",
"Shifting Bass Patterns",
"Noise Sweep",
"Synth Upright Bass",
"Dark Heavy Bass",
"Solid Body Bass",
"Brassy Ensemble",
"Warm Synth Pad",
"Time Warp Synth",
"Simple Short Pluck",
"Synth Woodwind",
"Short Swell Synth",
"Dirty Pulse",
"Tuned Metallic Click",
"Main Room Pluck Lead",
"Pensive Pluck",
"Hammered Wood",
"Sticky Percussion",
"Hammered Mallets",
"Chimera Hammer",
"Small Metal Box",
"Mutant Keys",
"Synth Piano",
"Wooden Keys",
"Percussive Pluck",
"Short Synth Patterns",
"Bright Plucked String",
"Big Square",
"Grungy Horn Hits",
"Mech Growl",
"Lo-Fi Throat",
"Flutter Pluck",
"Deep Abyss",
"Liquid Gold",
"Designer Bass",
"Aluminum Sweep",
"Grinding Waves",
"Electric Blue",
"Shimmering Bass",
"Fizzy Sweeper",
"Tin Man",
"Fast Talker",
"Gravity",
"Flying Machine",
"Urban Grunge",
"Hollow Pluck",
"Sweeping Scrape",
"Screech Bass",
"Filthy Bass",
"Artificial Persona",
"Massive Why",
"Iron Bass",
"Metallic Waves",
"Metal Sweep",
"Super Saw Inferno",
"Minor Outbursts",
"Short Sweet Plucks",
"Hammered Piano",
"Warm Glistening",
"Ambient Drift",
"Dreamt Of Metal",
"Diminished",
"Angry Microbes",
"Filter Resonances",
"Metallic Insects",
"Colossal Machine",
"Soul Spelunk",
"Swimming with Amoebas",
"Thinly Veiled Happiness",
"Abyss Reflections",
"Industrial Brain Grinder",
"Mid Atlantic Ridge",
"Shimmering Ascension",
"Fluttering Away",
"Hesitant Chaos",
"Squid Ink",
"In The Kelp Forest",
"Grunge Drone",
"Soft Fluctuations",
"Chrome Wave Space",
"Ambient Flutter",
"Slipping Far Away",
"Metallic Breaks",
"Liquid Choir",
"Machine Man",
"Swirling Motion",
"Tension Drift",
"Poseidon's Breath",
"Misses Muffle",
"Genetic Soup",
"Shimmering Metallic Atmosphere",
"Seas of Shining Mercury",
"Crazy Feedback Machine",
"Brushed With Tinfoil",
"The Gateway",
"Liquid Metal",
"Stuck in the Mud",
"Rusty Ship Engines",
"Sea Cucumber",
"Far Away Droning",
"Jocks Custard",
"Gently Glitching Organ",
"Liquid Iron",
"Its Not My Fault",
"Aqueous Ripples",
"Cloud Formations",
"Vintage Sci-Fi Space",
"Massive Ambient Drone",
"Minor Morphs",
"Crustacean",
"Spooks",
"Undulations",
"Late Night Tension",
"Haunted Drone",
"Diving With Shipwrecks",
"Harmony From Dissonance",
"Mud Slide",
"Calm Sunrise",
"Eerie Dissonance",
"Cluttered Atmosphere",
"Droid Communication",
"Rise From The Darkness",
"Intentions",
"Troll Transform",
"Cartoon Alien Soup",
"Fluid Traveling",
"Wing Jab",
"Modulating Landscape",
"Deep Currents",
"Hallgrimskirkja Bell Texture",
"Dark Drone Space",
"Skeleton Key",
"Wind Ambience",
"Gargle Choir",
"Haunting Piano",
"Massive Wall Of Noise",
"Crystal Caves",
"Rabbit Hole Infinity",
"Uncertain Future",
"Archipelago",
"Flanged Weather",
"Swirling Mass",
"Soft Psionics",
"My Warrior",
"Armor Shield",
"Waves and Rain",
"Dark Arrangement FX",
"Citadel Brass",
"Ring Mod Phased Drone",
"Vox Vinyl FX1",
"Storm Wall",
"Drop",
"Multiple Piercings",
"Ancient Starship",
"Vox Impact",
"Temporal Transition Telemetry",
"Filtering Glitch",
"Fast Risers",
"Huge Ambient Drum Wash",
"Screaming Whammy",
"Vox Vinyl FX2",
"Tinkles",
"Reptile Harpsichord",
"Stargate Opening",
"Liquid Ambience",
"Robotic Cave Crabs",
"Percussion Flurry",
"Tectonic Shift",
"Dangerous Falling Rocks",
"Sharp Resonant Hit",
"Eerie Atmosphere",
"Monsters Munching",
"Rain on a Tin Shed",
"Glitch Guitar",
"Tiny Laser Blaster",
"Interlocking Gurgles",
"Feedback Drone",
"Calm Beach",
"Jurassic Formula",
"Gloomy Shots Kit",
"Alien Transmission",
"Retro Space Ambience",
"Troll Bridge",
"Descending Hopes",
"Bass Metals",
"Only Chaos",
"Step Up Bass",
"Lava Lake",
"Aftershock Rumble",
"Binaural Beat",
"Asian Song",
"Fork Station",
"Ring-O-Stars",
"Looming In Shadows",
"Banshee",
"Fluttering Night Wings",
"Strange Alien Chant Generator",
"Laser Canon",
"Windstorm",
"Machine Communication",
"Blocks Into Grains",
"Metallic Bonks",
"Mad Crazy Glitch",
"Bionic Caution",
"Unexpected Situation",
"Slam Castle Gate",
"Guitar Avant-Garde",
"Random Ice Hit",
"Sweet Shots Kit",
"Sci-Fi Talk",
"Sizzling In The Kitchen",
"Arctic Winds",
"Deep Breath",
"The Fear Awakens",
"Space Wanderer",
"Crackle Drop",
"Artificial Heartbeat",
"Divergent Poles",
"Nonsense",
"Ancient Temple",
"Static Tunnel",
"Quad Modulations",
"Devil In The Deep",
"Nest of Snakes",
"Air Vent Impact",
"Twisted Metal",
"Flute Step",
"Tongue Tied",
"Caffeine Effect",
"70s Space Twinkles",
"Circuit Bent Banjo",
"Auroral Discharge",
"Thin Gong Echoes",
"Transitional FX Loops",
"Conference of Robots",
"Tuning Into Cosmic Radio",
"Zap Away",
"Huge Turbine",
"Enormous Iron Box",
"Ratcheting",
"Chaos Control",
"Warp Field Disruptor",
"Drunken Ghost",
"Tube Toner",
"Holding You",
"Deeper Space Zap",
"Ice Horror",
"Twinkles",
"Freaky Forest",
"Groaning Creature",
"Iron Kingdom",
"Wall of Analogue FX",
"Synthetic Waterphone",
"Static Mess",
"Spacecraft",
"Eerie Creep",
"Alarming",
"Black Heart",
"Wind Up Chaos",
"Flanging Motor",
"Dark Skies",
"Laser Sword",
"Deep Cave",
"Matador",
"Huge Hit",
"Speaking From Mars",
"Beast Growling",
"Magic of Nature",
"Antimatter Implosion",
"Massive Slam",
"Automatons",
"Flying Saucer",
"Mechanoid Walker",
"Eerie Landscape",
"Empty Caves",
"Step Wind",
"Machine Language",
"Jumaana Rain",
"Chaotic Pattern Echoes",
"Hard Stereo Noise Burst",
"Damaged Artifact",
"Alien Dog Affection",
"Fear of Nature",
"Binary Infiltration",
"Slowing Hopes",
"Bell Atmosphere",
"Down The Rabbit Hole",
"Jettison Plasma",
"Megaton",
"Colors Through Crystal",
"Pizzicato Sticks",
"Fire Plasma",
"Big Bangs",
"Metal Dome Impact",
"Vox Vocal FX",
"Mutant Guitar FX Kit",
"Mega Oscillations",
"Digital Drain Pipe",
"Glitch Clouds",
"Pitch Fall",
"Blueprint",
"Dripping",
"Transforming Machine",
"Genetic Code",
"Endgame",
"Invaders",
"Stretched Cymbal Scrapes",
"Beyond A Locked Door",
"All The Fun Of The Fair",
"Cave Insects",
"Alien Stomp",
"Glitch Machine",
"Swoosh",
"Citadel Synergy",
"Interstellar Communication",
"Data Storm",
"Granular Dub Echo",
"Communicator",
"Space Invasion",
"Warp Core",
"Ricochet",
"Envelope Asylum",
"Scrambled Comms",
"Steampunk Gothic",
"Monster Revealed",
"Citadel Throat",
"Dark Impact",
"The Grudge Effect",
"Eternal Engine",
"Haunted Child",
"Falling Rock Repetitions",
"Ring Mod FX Falls",
"Binaural Prepared Harpsichord",
"Universal Destruction Device",
"Space Station Repairs",
"Space Warp",
"Garden Sanctuary",
"Funny Aliens",
"Under The Mountain",
"Fire Ball",
"Random Monsters",
"Approaching Reality",
"Storm Clouds",
"Aquatic Strumming",
"Avant-Garde Ensemble",
"Universe Expanding",
"Fast Diving Spinner",
"Another Alien World",
"Subsonic",
"Space Craft Liftoff",
"Battle Drums",
"Strange Voice Cloud",
"Faster And Faster",
"Colossal Uprising",
"Space Docking",
"Time Stretch",
"Disturbing Chatter",
"Sweeping Hatter",
"Complex Orchestra",
"Adrift In The Void",
"Rapid Eye Movement",
"After The Rain",
"Warm Rain",
"Enchanted Soundscape",
"Arctic Breeze",
"Atmosphere At Dusk",
"Glacial Forms",
"Morning Meditation",
"Crystal Spheres",
"Warm Dust",
"Dark Choral Soundscape",
"Snow Drift",
"Dusty Strings",
"Texture Machine",
"Thunderous Ambience",
"Warm Winter Day",
"Warm 70s Bass",
"Mystic Timepiece",
"Carbon Particles",
"Vintage Dreamscape",
"Long Forgotten",
"Slow Breaths",
"Final Twilight",
"Distant Memories",
"Warm Flutters",
"Lustrous Nightfall",
"Hexagon Space",
"Cinematic Suspense",
"Crystalline Structures",
"Lo-Fi Voices",
"Endless Stratosphere",
"Aurora Waves",
"Beyond Deep Skies",
"Vintage Pluck",
"Repetition of Thought",
"Ice Blinks",
"Glitter Noise",
"Distant Harp Echoes",
"Ethereal Bells",
"Charm Bells",
"Dreamy Dulcet Bells",
"Summer Tines",
"Clouds of Mercury",
"Curious Hammers",
"Soft Keys",
"Warped Pluck",
"Mountain Rain",
"Sparkling Fireflies",
"Dreamy Air Guitar",
"Blinking Lights",
"Sleep Pulse",
"Dew Drops",
"Icy Caverns",
"Constellation Map",
"Star Arp",
"Clockwork Melodies",
"Glow Worms",
"Moonlight Glimmer",
"Polymetric Structures",
"Phased Cathedral",
"Classic Pop Analog Strings",
"70s Synth Strings",
"String Machine",
"Retro Analog Synth Strings",
"Strings Morph",
"Wide Analog Synth Strings",
"Mellotron Violins",
"Smooth Wavering Pad",
"Mini Saw Lead",
"Square Squad",
"Funk Boogie Synth Lead",
"Analog Sync Decay Lead",
"Triangular Phase",
"Robot Learning To Speak",
"Stretched Staccato",
"Sweet n Fuzzy",
"Sizzle Oscillator",
"Fluttering Patterns",
"Ana Lead Toolbox",
"Leads United",
"Ricochet Lead",
"Vox-like Lead",
"Flex Lead",
"Analog Mellow Lead",
"Resonant Sweep",
"Retro Synth Bells",
"Oddity",
"Bright Glide Lead",
"Grainy Blows",
"Classic 70s Funk Lead",
"Monstrous Synth Stack",
"Time Wind",
"Crazy Diamond",
"Soft Velocity Attack Lead",
"Punchy 80s Synth",
"Epic Rift",
"Fifths Super Lead",
"Saw Glide Lead",
"Trance Lead Designer",
"Airy Synth Lead",
"Resonant Funk Solo",
"Anthem Hook Lead",
"Otherworldly Lead",
"Sweet Tremolo Keys",
"Classic 80s Epic Brass",
"Soft Distortion Lead",
"Purple Key",
"Funk Spike",
"Futuristic Synth Lead",
"Butter Cut Square",
"Flutter Lead",
"Wavetable Morph Lead",
"Soft Comb Lead",
"Classic 80s Synth Brass",
"Tempo Sync Morph Tremolo",
"Tokyo Futures",
"Soft 70s Lead",
"Bricks",
"Festival Saw Lead",
"70s Analog Synth Lead",
"Stretched Legato",
"Scream Sync",
"Dual Multipliers",
"Big 7th Lead",
"Psychedelic Lab",
"Space Rock Solo Lead",
"Luscious Analog Lead",
"Triangle Lead",
"Phase Saw",
"Pulse Width Fifths",
"Modern R&B Lead",
"Butter Cut Saw",
"80s Analog Bells",
"Sweeping Synth Lead",
"Crispy Glide Lead",
"Burst Of Light",
"Analog Unison Lead",
"80s Synth Pop Lead",
"Classic 70s Synth Lead",
"Classic",
"Hats Sequence",
"Hyper Spin",
"Resonant Sample and Hold",
"Rise Bubble Sine",
"Grainy Sample and Hold",
"Hyper-Spin",
"Shimmering Stars",
"Vintage Brassy Pad",
"Brass Response",
"Out Of Touch",
"80s Slow Pop Sweep",
"Brassy Pad Swell",
"Street Boogie",
"Space Brass",
"Jump",
"Oceanic",
"80s Pop Synth Brass",
"Prophetic Brass",
"Analog Dark Decay",
"Funk Buzz Bass",
"Black Leather",
"Analog Slow Sweep",
"80s Classic Synth Bass",
"Chaos Glide Bass",
"DnB Bass",
"Bass And Lead",
"Classic Lead Bass",
"Boogie Bass",
"Wave Layers Bass",
"Rotor Bass",
"Analog Sub Sonic",
"Steady Wobble Bass",
"Synth Mode",
"70s Synth Intro",
"Metrix Bass",
"Funk Boogie Synth Bass",
"Analogue Happiness",
"Old Soul Funk",
"Sweep Saw Bass",
"Resonant Sweep Bass",
"Parasite",
"Wet Willy",
"Block Bass",
"Juicy Funk Bass",
"Analog Dark Lead",
"Street Dance",
"80s Electro Bass",
"Space Dance Octaves",
"80s Synth Pop Bass",
"Deep Plucks",
"Music and Lights",
"Analog Tight Sync Buzz",
"Analog Monster Punch",
"Vintage Resonant Bass",
"Deep Solid Bass",
"Oxygen Bass",
"Analog Saw Punch",
"Fire Hose",
"Ultra Fat Bass",
"River Of Sub Bass",
"Analog Dark Bass",
"Funk Bass Sweeper",
"Analog Funk Bass",
"Four Wave Morph Pad",
"Swirling Combs",
"Widely Serene",
"Majestic Waves",
"Density Sine",
"Deep Space Sweep",
"Sea Wave",
"Luscious Sweeps",
"Phased Beauty",
"Resonant Sweeps",
"Pulse Sweep",
"Loose and Swirly",
"Dark Universe",
"Filtered Squares",
"Swept Saw Pad",
"Mellotron Flute",
"Brightly Glistening",
"High Altitude Drift",
"Soft and Gentle",
"Analog Silk",
"Fuzzy VCOs",
"Analog Resonant Sweep 02",
"Folded Fifths",
"Analog Resonant Sweep 01",
"The Wanderer",
"Wavetable Morphs",
"Angelic Analog",
"Slow Dual Formant Pad",
"Double Bandwidth Pad",
"Luscious Waves",
"Flange Balm",
"Warm and Soft",
"Q Sweep",
"Lunar Pools",
"Dual Ring Mod Pad",
"Warm Vintage Analog Pads",
"Candy Pop",
"Oxygen Strings",
"Vowel Phasing",
"Band Pass Luster",
"Triangle Pad",
"Chorused Dirt",
"Obie Warmth",
"Analog Pulse Pad",
"Layer Synth Pick",
"Aqua Motif",
"Crossing Destiny",
"Southern Living",
"Needle Fraction",
"Suburban",
"Midnight Jupiter Keys",
"Bright Sky",
"Ensemble Power Pluck",
"Synth Pop Pick",
"Retro Synth Pluck",
"Sine D.N.A.",
"Soft Fun",
"Electronic Rose Keys",
"Sweet Dreams Pick",
"Velocity Duelists",
"Cream Pie",
"Tokyo Pick",
"Poly Synth Forever",
"Editorial",
"Pumping Out Waves",
"Power Lurks Within",
"Wide Splashy Pad",
"Pulses and Pad",
"Vintage Obsession",
"Pure Poly Synth Stack",
"Lush Meadows",
"Phasers Set to Stun",
"Skylight",
"Aluminum Bandpass",
"Phase Square Pick",
"Classic 80s Synth",
"Simple Analog",
"Poly Talking Synth",
"Mirror Objects",
"Binary Sun",
"Attack Sweep",
"Luscious Polyphony",
"Dust Synth",
"Mellow Synth",
"Soft Plucky Synth",
"Motion Pluck",
"Silver Saw",
"Fluid PWM Pick",
"Snow Fall Bells",
"Bending Around Synth",
"Pulse Sugar Pick",
"Ricocheting Phaedra",
"Mandrake Arp",
"Solid Modular",
"Microscopic Sine Waves",
"Modern Bass Arpeggiator",
"Chunky Arpeggio Bass",
"70s Analog Sequencer",
"80s Pop Synth Arpeggiator",
"Bouncing Comets",
"Berlin Oscillators",
"Dark and Soft",
"Hollow Psychedelic",
"Mod Arp Bass",
"Square Randomizer",
"Abstract Landscape",
"Ice Wind Morph",
"Heat Haze",
"Rising Thermals",
"Exquisite Visions",
"Morning Mist",
"Pulsating Resonance",
"Soft Play",
"Dark Forces",
"Iron Forest",
"Ocean of Metal",
"Reposessed",
"Forgotten Streets",
"Organic Binary",
"Cross Talk",
"Breathless",
"Reception",
"Warped Strings",
"Android Chamber",
"Electromagnetic Array",
"Fragments of Time",
"Bulkhead",
"Ambient Melody",
"Reconditioning",
"Shimmering Glitches",
"Darkness and Light",
"Fragile Dreamscape",
"Orbital Elevator",
"Skywriting",
"Possessed Robot",
"Particle Winds",
"Rusted Wasteland",
"Dark Whispers",
"Dark Abyss",
"October Rain",
"Alien Insect Infestation",
"Tormented",
"Infinite Tensions",
"Air Strings",
"Environmental Tension",
"Water Machine",
"Inhospitable",
"Crystal Cave Groove",
"Resonant Disorder",
"Sunbathing on an Iceberg",
"Ultra Cute",
"Inhuman Chanting",
"Metallic Drone",
"The Sea",
"White Out",
"Tuning Out",
"Stolen Memories",
"Electrical Pulses",
"Empathy",
"Urban Decay",
"Alien Ice Jungle",
"Transform Device",
"Complex Sequencer",
"Advanced Hydraulics",
"Space Whale",
"Fried",
"Spectral Tensions",
"Transmuted Materials",
"Particles Blender",
"Cosmic Impacts",
"Rumbling Waves",
"Mech Impact",
"Droid Room",
"Drive By Doppler",
"Chaos Vortex",
"Shapeshift Synth",
"Processing",
"Grain Droids",
"Receiving Transmission",
"Hidden Geology",
"Spiraling Downwards",
"Endlessly Variable Sci-Fi Alarm",
"Sludge Machine",
"Particle Fusion",
"Deharmonizer",
"Dark Eruption",
"Superposition Bends",
"Aural Cube",
"Slow Machine",
"Meta Growler",
"Terminal",
"Rise Above",
"Fusion Drive",
"Noise Tides",
"Swarm Riser",
"Sidechain Massive",
"Broken Signals",
"Triple Band",
"Dark Hammer",
"Growling Formants",
"Devastating Dark Bass",
"Titanium Edge",
"Concussion Bass",
"Sinus Deformation",
"Fragmentator",
"Communication Breakdown",
"Derailed Harmonics",
"Gravity Waves",
"Meditation Growl",
"Spectral Fusion",
"Dramatic License",
"Crushing Rust",
"Duality Synth",
"Primordial Elements",
"Raw Circuitry",
"Hypnotic Glitch",
"Gated Growl",
"Minor Incident",
"Deep Drum Wobble",
"Engine Room",
"Looming Beat",
"Mechanical Beat",
"Pluck Groove",
"Shudder To Think",
"Orchestral Circuits",
"Unraveled",
"Hydroelectric",
"Pneumatic",
"Bass Press",
"In Motion",
"Cyborg",
"Bellscape",
"Random Chatter",
"Harmonic Drift",
"Abandoned Pad",
"Swaying Trees ",
"Motorized Choir",
"Binary Star",
"Chain Reaction",
"Emotional Drift",
"Meditation Drone",
"Photons",
"Aluminium Angels",
"Comfort",
"Mercurial",
"Circuit Monks",
"Elsewhere",
"Steel Dreams",
"Strange Strings",
"Endless Mallets",
"Lo-Fi Exotica",
"Spare Change",
"Pressurized Voice Bubbles",
"Flopper",
"Celestial Vortex",
"Encoded Transmission",
"Alien Chorus",
"Light Speed",
"Echolocation",
"Fuel Cells",
"Ridiculous Speed",
"Unison Riser",
"Forever Riser",
"Ludicrous Speed",
"Plasma Drop",
"Pole Position",
"Motoriser",
"Vowel Disintegrator",
"Howling Riser",
"Adrenaline Rush",
"Trill Riser",
"Particle Accelerator",
"Liquid Light",
"Chopped Riser",
"Another Dimension",
"Cymbal Swell",
"Cosmic Storm",
"The Cathedral",
"Dystopian Soundscape",
"Stellar Space",
"Stationary Orbit",
"Bowing Alien Strings",
"Mellow Heart",
"Emotive Atmosphere",
"Wondrous Land",
"Metamorphic",
"Moonlight Comfort",
"Wave Memories",
"Fade Away",
"Infinite Drone",
"Stars Drifting By",
"Traveling at Speed",
"Peaceful Meadow",
"Cosmic Waves",
"Deserted Moon",
"Extraterrestrial Presence",
"Synthetic Chatter",
"Vocal Cluster",
"Unstable Storm",
"Subaquatic Dreams",
"Soundscape 1992",
"Lost Reverse",
"Nocturnal Airstream",
"Gong Atmosphere",
"Shimmering Void",
"Underwater Temple",
"Secret Garden",
"Calm And Storm",
"Space Station Drone",
"Space Continuum",
"Portal in the Ocean",
"Waves Upon Waves",
"Fluttering Drones",
"The Black Swamp",
"Unstable Crystals",
"Moon Language",
"Halo Tines",
"Stretched Crotales",
"Meditation Sphere",
"Wall Of Distortion",
"Crystal Caverns",
"Pale Apparition",
"Daylight Apparition",
"Diffused Liquid",
"Visions of Pyramids",
"Freezing Fog",
"Turing Machine",
"Mystical Vox",
"Bowed Metal Space",
"Vintage Sci-Fi Ambience",
"Magnificent Drone",
"Ambient Guitar Landscape",
"Action Drums",
"Cutting Through Ice Caves",
"Demented Percussion",
"Percussive Hit",
"Future Junglist",
"Impact Effects",
"Voice Becomes Flute",
"String Vox",
"Voice Plucks",
"Vocal Waves",
"Dark Movements",
"Vowel Glider",
"Vocoded Ice Vox",
"Heavenly Vox",
"Tubular Clockworks",
"Mystical Voice",
"Vowel Pad",
"Ghostly Voices",
"Interrupted Voices",
"Cosmic Boys Choir",
"Vox Box Lead",
"Metallic Edge Lead",
"Gigantic Edgy Lead",
"Smooth Analog Lead",
"Paper Thin Lead",
"Icy Synth Lead",
"Retro Space Lead",
"Fuzz Sweep Bass",
"Luminous Chaos",
"Classic Techno Lead",
"Celtic Flute And Strings",
"Mysterious Synth Lead",
"80s Sync Lead",
"Thin Metal Waves",
"Evolving Currents",
"Titanic Elevations",
"Epic Hook Synth",
"Wobble Lead",
"Buzz Fuzz Phaser Bass",
"Dark Edgy Lead",
"Anthemic Sync Lead",
"Liquid Breath Flute",
"Glass Butterfly",
"Buzzing Metallic Lead",
"Rising High Synth Lead",
"Sweet Lead",
"Supersaw Lead",
"Techno Chord Hit",
"Serpentine Bite",
"Funk Splash Lead",
"Unlikely Brass",
"Unity Synth Lead",
"Short Plucky Synth",
"Heavy Handed Bass",
"Old Robot Factory",
"Glitching Machine",
"Neverending Riser",
"Stretched Dream",
"Alien Percussion",
"Descending Below",
"Club Siren",
"Transform Flare",
"Sci-Fi Communications",
"Aquatic Metalworks",
"Moment Of Impact",
"Blurry Machinery",
"Sheets Of Metal",
"Space Impacts",
"Laser Catastrophe",
"Dark Alien Bells",
"Liquid Warp",
"The Dark Abyss",
"Transmutation",
"Swarming Arp",
"Robotics Machinery",
"Backwards Metal",
"Transformative Effect",
"Big Hollow Bass",
"High Voltage Wobble Bass",
"Deep Synth Bass",
"Vintage Brassy Bass",
"Growling Synth Bass",
"Mega Wobble Bass",
"Future Wobble Bass",
"Chip Tune Lead",
"Dirty Funk Bass",
"Massive Wah Bass",
"Slow Nasty Rise",
"Pumping Synth Waves",
"Boxy Synth Bass",
"Deep Techno FM Bass",
"Gritty Wobble Bass",
"Liquid Square Bass",
"Classic Funk Boogie Bass",
"Wobble Buzz Bass",
"Thumping Kick Bass",
"Nimble Synth Bass",
"Sinister Bass",
"Massive Grime Bass",
"Deep Growling Vox Bass",
"Nouveaux 80s Bass",
"Deep Distortion Pulse",
"Sharp Wobble Bass",
"Frozen Bass Waves",
"80s FM Bass Attack",
"Synth Bass Mutation",
"Analog Bass Twister",
"Colossal Synth Bass",
"Classic Funk Synth Bass",
"Dark Bass Drive",
"Fizzy Layered Bass",
"Agile Synth Bass",
"Heavy Wobble Bass",
"Heavy Sync Bass",
"Torn Up Wobble Bass",
"Oversized Dub Wobble",
"Tight Synth Bass",
"Edgy Synth Bass",
"Taureg Moon Bass",
"Dark Currents",
"Modern Synth Bass",
"Moving Anthem Lead",
"Grinding Rhythm",
"Liquid Vox Lead",
"Heavy Synth Bass",
"Dirty Wobble",
"Filthy Slap Bass",
"Dirty Growling Bass",
"70s Classic Synth Bass",
"Voice Bass",
"Deep Sub Bass",
"Layered Kick Bass",
"Deep Techno Bass",
"Enigma Bass Machine",
"Arctic Noise Lead",
"Monster Bass",
"Grunge Wobble Bass",
"Detuned Ghost Bass",
"Mighty Synth Bass",
"Scream Bass",
"Heavy Sub Bass",
"Neon Synth Bass",
"Plucky Synth Bass",
"Modern 80s Bass",
"Vacuum Packed",
"Noisy Slap",
"Crunchy Synth Patterns",
"Dominating Machines",
"Orbital Clockwork",
"Deep Bass Patterns",
"Animated Swirls",
"Walking Creature",
"Percolating Mercury",
"Glitching Beat Machine",
"Harmonic Tides",
"Techno Bass Patterns",
"Sweeping Waves",
"Bass Patterns",
"Synthetic Synergy",
"New Psychology",
"Snow Cycles",
"Pulsing Patterns",
"Cloud City",
"Rhythmic Resonator",
"Sidechain Electro Bass",
"Minimal Acid Patterns",
"Classic House Sequence",
"Rhythmic Noise Flurry",
"Rhythmic Vox",
"Synth Pop Riff",
"Rough Wave Patterns",
"Rhythmic Reflections",
"Metallic Fireflies",
"Turbulent Beat Machine",
"Tough Bass Patterns",
"Rhythm Ghost",
"Tube Pluck Pattern",
"Hypnotic Synth Bass",
"Mind-Bending Patterns",
"Synth Texture Patterns",
"Crystalline Rhythms",
"Minimal Techno Pattern",
"Pulsating Soundscape",
"Waves Of Mercury",
"Pulsing Harmonic Movement",
"Structured Waves",
"Short Sticky Patterns",
"Android Funk",
"Ethnic Percussion Pattern",
"Gene Splicer",
"Neurons Firing",
"Shimmering Harmonics",
"Noisy Ghost Rhythm",
"Rhythmic Robotics",
"Drifting Pulsations",
"Step By Step",
"Moment Of Indecision",
"Scattered Rhythm",
"Very Large Clock",
"Plucking Ambience",
"Unstable States",
"House Chords",
"Electro Bass Patterns",
"Groove Pattern Pad",
"Geometric Patterns",
"Pumping Electro Bass",
"Transformative Beat",
"Future Screamer",
"Multiple Material Machine",
"Electro House Patterns",
"Machines In Harmony",
"Loop Mangler",
"Noise Patterns",
"Pulsating Wobble",
"Groovy Synth Pattern",
"Synth Bass Patterns",
"Single Digit Drama Pattern",
"Sci-Fi Suspense Theme",
"Step Gate Pulsar",
"Machine Looper",
"Deep Electro Bass Pattern",
"Alien Space Probe",
"Grooving Pulsations",
"Digital Machine Patterns",
"Echolocation Synth",
"Moonrise Space Walk",
"Drifting Away",
"Interdimensional Traveler",
"Drifting In Hyperspace",
"Luscious Sweeping Pad",
"Sun Glitters Pad",
"Celestial Voices",
"Remembering Summer",
"Infinite Fields",
"Vintage Flyers",
"Noise Storm",
"Cumulus Choir",
"Haze Over Water",
"Awaken From Dark Dreams",
"Swirling Flutters",
"Cloud Shimmer",
"Light Harmonics",
"Ghost Voices",
"Made From Star Dust",
"Slow Swell Shimmers",
"Orbiting Jupiter",
"Blue Air",
"Digital Meditation",
"Titanic Waves",
"Cloud Diving",
"Epic Cloud Formation",
"Sunset 1977",
"Mercury Lake",
"Celestial Organ",
"Trickling Ice Crystals",
"Gentle Rain Shower",
"Breathless Space",
"Flying Home",
"Crystal Sun",
"Hypnotic Bliss",
"8mm Film Sequence",
"Dream Sines Pad",
"Ensemble Ultima",
"Luminous Sweep Pad",
"Aether Choir",
"Space Waves",
"Solar Storm",
"Sweeping Vistas",
"Ocean Sun Glitters",
"Deep Waves Pad",
"Darkness Beckons",
"Morphing Ensemble",
"Sunrise 1984",
"Spacey Echo Bells",
"Vox Synth Pad",
"Infinity Pad",
"Intergalactic Contact",
"Dream Voice",
"Slow Attack Piano",
"Days End",
"Tidal Space",
"Emerald Haze Pad",
"Granular Vox",
"Dark Percussion Layers",
"Mighty Wobble Bass",
"Liquid Synth",
"Vox Box Synth",
"Metallic Echo Tines",
"Noisy Metal Bells",
"Soft Synth Bells",
"Unstable Liquid Synth",
"Bright Punchy Synth",
"Analog Bubbles",
"Cyclical Waves",
"Sea Of Sines",
"Luminous Corridor",
"Splashy Waves",
"Journey To Pluto",
"Shiny Silver Synth",
"Lights and Mirrors",
"Glistening Dust",
"String Dreams",
"Howling Space Synth",
"Analog Stack Synth",
"Talking Bee Bass",
"Detuned Drones",
"Otherworldly Oceans",
"Synth Bell Layers",
"Lo-Fi Synth",
"Acid Etched Bass",
"Hold And Dissolve",
"Supervillain Brass",
"Coral Garden",
"Liquid Wires",
"Sunshine Thru Clouds",
"Synth Bell Atmosphere",
"Wire Choir",
"Waves Motion Bass",
"Spectral Pizzicato",
"Noisy Bell Pad",
"Tight Synth Chord",
"Ocean Flow",
"Knocking Echoes",
"What I Am",
"Shimmering Bells",
"Kalimba Morph",
"Metallic Bell",
"Golden Bowl Mallets",
"Nighttime Bells",
"Clockwork Ballerina",
"Dark Mallet Layers",
"Ice Mallets",
"Chimera Bells",
"Hybrid Mallet",
"Hybrid Metal Mallet",
"Brassy Glass Bells",
"Suspended Bells",
"Chimera Keys",
"Versatile Electric Piano",
"Solid String Pizzicato",
"Unfolding Paper Bells",
"Luminous Tines",
"Spooky Bells On Vinyl",
"Crystal Bells",
"Distant Vintage Organ",
"Outer Lands Synth",
"Old Fragile Vinyl Keys",
"Gentle Sine Bells",
"Antarctic Sun",
"Dusty Record Synth",
"Retro Keys",
"Titanic Anthem",
"Gaseous Lead",
"Xylophone Keys",
"Modern Hybrid Keys",
"Mellow Chimes",
"Water Rings",
"Harmonic Taps",
"Rain Strum",
"Exotic Plucked String",
"Beautiful Synth Harp",
"Dulcimer Harp",
"Exotic Metals",
"Eastern Hammers",
"Overdrive Grunge",
"Water Guitar",
"Beautiful Sine Harp",
"Morph Example",
"Old Space Piano",
"Lush Arp Layers",
"Synthetic Gamelan Arp",
"Random Echoes",
"Smooth Synth Arp",
"Analog Bass Sequence",
"Groove Pulse",
"Gamelan Bells",
"Layered Bass Arpeggiation",
"Wired Moments",
"Stringy Pluck Pattern",
"Deep Neural Patterning",
"70s Synth Arp",
"Arp Animations",
"One Android Band",
"Busy Arp Bass",
"Cosmic Arp Cycles",
"Shifting Patterns Synth",
"Minimal Synth Pattern",
"Crystals and Voices",
"Sweeping Arp",
"Limber Loop",
"Deep Bass Pattern",
"Dream Pluck Patterns",
"Voyage To New Lands",
"1970s Analog Arp",
"Synth Pluck Patterns",
"Synced Noise Arp",
"Strange Bell Atmospheres",
"Jittery Pulses",
"Warm Arp Pad",
"Classic Arp Echoes",
"Music Vox",
"Anthem Chord Arp",
"Glass Mallet Patterns",
"Synth Burst Patterns",
"Plucked Wave Patterns",
"Metal Storm",
"Classic Acid Patterns",
"Plucked Echoes",
"Luscious Arp Layers",
"Pulsating Arp Bass",
"Scatter Chords",
"Almost Piano Arpeggiation",
"Blue Skies",
"Bell Echo Arp",
"Electron Patterns",
"Film Memories",
"Follow the Sines",
"Squelchy Synth Bass",
"Short Sync Arpeggiator",
"Glitch String Patterns",
"Gears And Springs",
"Digital Rain Drops",
"Single Digit Minor Arps",
"Droplets",
"Dancing Architecture",
"Deep Groove Synth Bass",
"Sci-Fi Synth Arp",
"Main Room Epic Arp",
"Liquid Echo Bells",
"Mode Selector",
"Time Runner",
"Modern Acid Patterns",
"Galactic Layers",
"Light Breaks Through",
"Big Anthem Arp",
"Star Dust Arp",
"Bright Majestic Waves",
"Shifting Arp Patterns",
"Sweet Luck Chime",
"Just About Brass",
"Boxy Room Pluck",
"Future Feels Brass",
"High Rise Pluck",
"Snapped Up Plucks",
"Dark Space Pluck",
"Simple Square Bells",
"Dark Bass Sweep FX",
"Grind Bass Sweep FX",
"Dark Secrets Bass",
"Classic Slap House Bass",
"Smooth Short Bass",
"Pumped Infinity Bass",
"Sliding Structure Bass",
"Rattle Punch Bass",
"Round and Punchy Bass",
"Dark Glide Bass",
"Round House Bass",
"Tight Percussive Bass",
"Strong Percussion Bass",
"Sharp Cut Bass",
"Resonant Pluck Bass",
"Majestic Rise Pad",
"Overstuffed 808 Bass",
"Destroyed 808 Bass",
"Grinding 808 Bass",
"Monster 808 Bass",
"Crushed 808 Bass",
"Hard 808 Bass",
"Heavy 808 Bass",
"Smashed 808 Bass",
"Impact 808 Bass",
"Massive 808 Bass",
"Solid 808 Bass",
"Lo-Fi Drive 808 Bass",
"Squeaky 808 Bass",
"Super Sub 808 Bass",
"Deep 808 Bass",
"Sweeping 808 Bass",
"Tough 808 Bass",
"Knocked 808 Bass",
"Gliding 808 Bass",
"Snappy 808 Bass",
"Pounding 808 Bass",
"Black Diamond",
"Blue Laser Lead",
"Percussive Drawbars",
"Clean Organ",
"Flexible Square Bass",
"808 Bass",
"Mutant Acoustic Bass",
"Breaking Bass",
"808 Mutation Bass",
"Cloud Bass",
"Full Sub",
"Pressure Drop Bass",
"Chill Vocal Sequences",
"Flutter By",
"Lush Pulse",
"Trill Bows",
"Dark Textures",
"Autumn Haze",
"Connect Chords",
"Reminisce Keys",
"Chop It Up",
"Spacetime Keys",
"Faded Keys",
"Chill Keys",
"Bass Keys",
"Odd Key",
"Gritty Bells",
"Guitar Gliss",
"Six String Gliss",
"Cosmic Theory",
"Curious Alien",
"Scary Zone",
"Inbetween Spaces",
"Transition Into Flight",
"Precursor",
"Dark Corridors",
"Gravity Gate",
"Dark Times",
"Aquatic Chaos Generator",
"Twitch In The Wires",
"Mountain View",
"Long Spooky Atmosphere",
"Broken Clockwork Bells",
"Organ Grinder",
"Robot Factory Ambience",
"Cosmic Vibrations",
"Deception",
"Enemy Atmosphere",
"Blowholes From Mars",
"Rain Of Elysium",
"Gas Giants",
"Ominous Arrival",
"Carnival Of Dreams",
"Subterranean Winds",
"Large Hadron",
"Pluto Protocol",
"Additive Corkscrew",
"Aquatic Cloud",
"Black Arts Lab",
"Deep Spiral",
"Ghost Sprinklers",
"Mystical Patterns",
"Objects in Space",
"Charmed Future",
"Metal Fingers",
"String Swirl",
"Final Darkness",
"Bowed Abandon",
"Twitchy",
"Empty Space",
"Mallet Rattlers",
"Airplanes",
"Frozen Cave Atmosphere",
"Drama Wire",
"Vox Cloud",
"Dark Skies Above",
"Malfunctioning Bell Pad",
"Doomsday Moment",
"Deep Blue",
"Philosophers Journey",
"Cascading Moon",
"Awe Inspiring",
"Particle Surge",
"Neptunes Titan Choir",
"Spatial Dressing",
"Levitation Engine",
"Glass Cutter",
"Benevolence",
"Beauty Sleep",
"Haunted Bell Tree",
"Ghost Ship Lost In Fog",
"Hungry Ghosts",
"Thru the Comets Tail",
"Random Madness",
"Foundry Bells",
"Hollow Asteroid",
"Odd Floor",
"Messages From The Expanse",
"Solar Flares",
"Stargazer",
"Unknown Atmosphere",
"Dust Storm",
"Recurring to Infinity",
"Apparition Passing By",
"Clav Wash",
"Fifth Quadrant",
"Silver Clouds",
"Mongolian Throats",
"Calling Darkly",
"Ambivalent",
"Turbulent Swells",
"Flow",
"Spinning Metal Blades",
"Hydroponic Garden",
"Pulsation String",
"Dramatic Tension Patterns",
"Moonlight",
"Underwater Factory",
"Deep Forest",
"Cadence Of Triton",
"Thru Clouds",
"Aquaculture",
"Lonely Amoeba",
"Method of Transference",
"Lost City",
"Black Hole",
"Travelling Angels",
"Random Cold Shiver",
"String Torture",
"Backwards Dream",
"Moody Hall",
"Deep Eerie Space",
"Single Digit Epic Chord",
"Machine City",
"The Deep Down Under",
"The Fear",
"Reveal In Darkness",
"Dark And Scary",
"Creaking Timbers",
"Confusion Machine",
"Ice Crush",
"Plunging Oceans Deep",
"Internalized Tension",
"Coffee Addict",
"Alien Atmosphere",
"Clockwork Angel",
"Plucking Space Strings",
"Mesmeric Modulator",
"Gloomy Apparition",
"Outside",
"Abandoned Space Station",
"Breath and Roar",
"Butterflies",
"Drifting Void",
"Sorrow Ambient Kit",
"Apparition Materialized",
"Spaceship Navigation",
"Planet Zero",
"Swishing Ambient Pad",
"Tibetan Monks",
"Aftermath",
"Choir In A Distant Cave",
"Undercover String",
"Dreamport 9",
"Aquatic Dreamscape",
"Alchemy In Wonderland",
"Deep Space Communication",
"Angels On Pluto",
"Bowed Metal Pipe",
"Martian Atmosphere",
"Moonshine",
"Cosmic Bells",
"Systematic Ensemble",
"Sound Of Space Traffic",
"The Lost Chord",
"Cone Pressure",
"Desolate Subterranean",
"Clouds in the Headroom",
"Cryogenic Sleep",
"Mesopotamian Treasure",
"Accelerating Particles",
"Hemisphere",
"Distant Shores",
"Memory Capsule Factory",
"Neuron Deep",
"Descending Deep Down",
"Shifting Sands",
"Omega Lights",
"Machine Awakens",
"Epic Guitar Hall",
"Deep Reflections",
"Lurking In Shadows",
"Number Six",
"Night Falls Quickly",
"Sizzle Blurry",
"Solar Waves",
"Celestial Waves",
"Interstellar Whale Calls",
"Bursts Into Echoes",
"Cat In The Piano",
"Space Station Construction",
"Amazonia",
"City Strums",
"Dark Doesnt Matter",
"Work of Fairies",
"Bubble Breathing",
"Long Tunnels",
"Figment",
"Here Come The Machines",
"Gothic Overdrive",
"Endless Rotation",
"Balinese Temple",
"Ancient Alien Pilot",
"Blue Bubbles Atmosphere",
"Emptiness Ambient Kit",
"The Melodious Vowel Piano",
"Dark Synth Choir",
"Spectral Choir Phrases",
"Girls Choir-Sibilant Harmony",
"Choir Freeze",
"Choir Girls",
"Gentle FM",
"Voices",
"Voices In The Clouds",
"Girls Choir Granular-Andvari",
"Voice Scanner",
"Songhellir-Granular Choir",
"Deep Harmonic Waves",
"Choir Grains",
"LoFi Vinyl Choir Organ",
"Moving Voice",
"Nasal Motion Choir",
"Humanoid Choir",
"Divine Voices",
"Mutated Choir Phrases",
"Chaotic Machine Patterns",
"Moon Harvest",
"Marco Polo in 3021 A.D.",
"VeVa Rhythm",
"Syncopated Vowels",
"Out of Orbit",
"Bellarophon Sector",
"Singing Synth Chords",
"Broken Beat Glitch Loop 02",
"Loop Construction Kit",
"Considered Response",
"Broken Beat Glitch Loop 01",
"Fairy Phrases",
"90s Wave Sequence",
"Pattern Morphs",
"Dantes Fall",
"Granular Flurries",
"1 Note Chord",
"Another New Adventure",
"A Bunch Of Beats",
"Chaotic Uprising",
"Kick Synth Pattern",
"Stiletto Race",
"Automaton",
"Primary Colors Rhythm",
"Moments Before Sunrise",
"Crystal Pulse",
"Metamorphosis Techno Loop",
"The Last Theater",
"Dying Angel",
"Inkling Pad",
"Magic Bells",
"Insubstantial",
"Science Sisters",
"Rain Over Water",
"Good Life",
"Lovely Voices",
"Endless Beauty",
"Freezer Pad",
"Humility",
"Harmonic Space",
"Can Of Worms",
"Vector Untitled",
"Luscious Bell Layers",
"Vintage Saw Pad",
"Rays of Light",
"Wandering Voices",
"Offshore",
"Elephants",
"Clouds Of Suns",
"Before The Storm",
"Crystalized",
"Evolved",
"Nature Pad",
"Dolphin Experiences",
"Behind Bridges",
"Rich Swirly String Synth",
"Clarity Of Purpose",
"Blue Sphere",
"Farewell Pad",
"Blue Strand",
"Wuthering Highs",
"Aurora Over Gjogursvatn",
"Autumn",
"Long Distance Light",
"Uplifting",
"Cloud Chorus",
"Forgotten Time",
"On The Edge Of Sleep",
"The Morph",
"Swirling Above Clouds",
"Aurora Over Iceland",
"Bionic Interference",
"Drifting Down Stream",
"Bizarre Pad",
"Rising High Above",
"Pragmatic Strike",
"Spatial Drift",
"Angelic Choir",
"Deca Swirls",
"Chameleon Pad",
"Soft Space Drift",
"Folding Space",
"Sci-Fi Landscape Pad",
"Eternal Longing",
"Interstellar Discovery",
"Classic Simple Pad",
"Lilac Ghosts",
"View From The Summit",
"Epic Swell",
"Mystic Pad",
"Gong Pad",
"Mountain Fog Rolling In",
"Vox Harmonium",
"Eternal Uncertainty",
"Swept Away Pad",
"Hotel Endless",
"Distant Obscure Beacon",
"Symbol of Stones",
"Stolen Beauty",
"Purity of the Huldufolk ",
"Endless Ocean",
"Forming Ice Crystals",
"Astral Oracle",
"Civil Calculation",
"Swift Breeze",
"Wide Metamorphic",
"Aurora Haze",
"Hymn",
"Gates of Heaven",
"Firehouse",
"Lush Ambient Waves",
"Slow Planet",
"Colossus",
"Vox Choir",
"Lunar Eclipse",
"Sand Dunes",
"Angelic Ghosts",
"Slow Rising Sun",
"Solemn Echoes",
"Granular Stutter",
"No Warping Allowed",
"Esoteric Vision",
"Echoes Pad",
"Graded",
"Rising From The Deep",
"The Big Wash",
"Waves On Mars",
"Cosmic Vox Morph",
"Ocean Science",
"Breath Control",
"Transmissions",
"Synth Pad Vox Layers",
"Fake Choir",
"Salt Mist",
"Gothic Organ",
"Hissing Machinations Pad",
"Hope in Dystopia Pad",
"Music Box Helper",
"Slow-Moving Waves",
"Structural Continuum",
"Aquamarine Static",
"Last Swap",
"Endless Universe",
"Liquid Morph",
"Floating Formants",
"Rings Of Saturn",
"Drunken Ships",
"Juxtaposed",
"Up In The Air",
"Tight Vox Pad",
"Euclidean Space",
"Silver Stripes",
"Magic Stone",
"Sweeping The Expanse",
"Sparkle Motion",
"Vox Halo",
"Lonely Ocean",
"Massive Swirling Pad",
"Late Broken City Pad",
"The New Polychrome",
"Traveling Through Space",
"Angel",
"Glow Worm",
"Ocean Voices",
"Expansive Guitar Pad",
"Metallic Gating Patterns",
"Stem Cells",
"Enveloped In Warm Air",
"Harvest Pad",
"Granular Glisters",
"Combed Mms",
"Lonesome Calm",
"Voice Noise",
"Spun Chiffer",
"Vortex",
"Cyclone Viewed From Space",
"Peaceful Valley",
"Guitar Harmonics Pad",
"The Journey Home",
"Static Haunt",
"Sigh Sisters",
"Ancient Traveller",
"Canyon Clouds",
"Green Carrot",
"70s Space Pad",
"Vox Pad Layers",
"1940s Choir",
"Beautiful Ascent",
"Umbrella",
"Summit View",
"Calm Over Eyjafjallajokull",
"Mega City Fifth",
"Analog Osmosis",
"Sweet Resonance",
"Secret Dawn",
"Behold Atlantis",
"Deviation",
"Ethnic Traveller",
"Bite String",
"Meditation Bells",
"Fuzzy Bars",
"Grasshopper Keys",
"Dream Lead",
"Bright Wave Synth",
"Organic Munchkin",
"Avatar",
"Greet the Dawn",
"Sonic Shelter",
"Interlude",
"Dali et Bleu",
"Linear Dimension",
"Stereo Delight",
"Single Digit Fingerpicking",
"Star Dome",
"Circuit Room",
"Bellatrix",
"Thoughts in Reverse",
"Another Day",
"Afterthought",
"Single Digit Melody",
"Terri Tory",
"Ominous Beginnings",
"Arcane Future",
"Bowed Metal",
"Midnight Arrival",
"Rusted Machine",
"Breathable Atmosphere",
"Colossal Brass",
"Opaque Deep Bass",
"Oblivion Pulse Bass",
"Heavy Pulse Bass",
"Resonant Deep Bass",
"Waves of Deep Bass",
"Grimy Silver Box Bass",
"Rounded Square Bass",
"Smooth Thump Bass",
"Hollow Frame Bass",
"Hybrid Elastic Bass",
"Crimson Cloudscape",
"Rising Tension",
"Elevated Construct",
"Structural Glitch",
"Polished Concrete",
"Shimmering Eternity",
"Aquatic Pulsations",
"Tektonic Grooves",
"Future Foundation",
"Vortex Structures",
"Alien Rainforest",
"Dark Moody Waves",
"Tight Synth Pluck",
"Sines of Structure",
"Punchy Synth Pluck",
"Shadow Piano",
"Metallic Dreams",
"Weighted Pluck",
"Distant Etherial Bells",
"Distant Bells",
"Object In Motion",
"Sleeping In The Hive",
"Waves of Enlightenment",
"Metal Pipes",
"Deep Space Drone",
"Kaleidoscope Skies",
"Nitrogen Port",
"Europa X-12",
"Air and Water",
"Alien Swarm",
"Organic Android",
"Ring Mod Atmosphere",
"Uncertain Voices",
"Drifting Embers",
"Let Her Go",
"Distant Battle Horn",
"Weather Pipes",
"Chantress",
"Endless Optimism",
"Persian Shack",
"Flying Through Clouds",
"Crypt Crawlers",
"Water Reflects Light",
"Song of the Sea",
"Demon Flange",
"Blow Hole",
"Scorch Marks",
"Dissonant Voices",
"Voice Of Sun",
"Glass Grumbles",
"Hush Voices",
"Obscured Voices",
"Subterranean Dream",
"Cold Sweat",
"Contemporary Villain",
"Whispered Dreams",
"Crystal Shards",
"Dust of Yesteryear",
"Hit Me",
"Woosh Snaps",
"Trompong",
"Gesture Drums",
"Warning Bell",
"Explore Top Drawer",
"Splash Snare",
"Water Jug Drums",
"Whip Kit",
"Knocking Percussion",
"Metallic Impact",
"Deep Hit",
"Pebble Snare",
"Snap Snare",
"Icelandic Choir SFX Kit",
"Tremolo Snare",
"Rock Kicks",
"Tin Can Hit",
"Cymbal FX Kit",
"Seaweed Glitch Kit",
"Underground Reservoir Tank FX Kit",
"Longevity",
"Steam Machine Kit",
"Low Long Drums",
"Travelling Gong",
"Thunder Drum Kit",
"Metallic Percussion",
"Delay Percussion",
"Rock Percussion",
"Buzz Gong",
"Massive Gong",
"Dirty Quantum Water Jug",
"Ice Fractures Kit",
"Quicksilver Multi SFX",
"Age Of Steam Kit",
"Girls Choir-Staccato-Da",
"Girls Choir-Staccato-Ee",
"Alchemists Choir",
"Choir-Female-Mm-Oo-Ah-Eh",
"Random Vowels",
"Land Of Snow And Ice",
"Choir-Female-Eh",
"Girls Choir-Oo",
"Choir-Mixed-Oh",
"Choir-Male-Oo",
"Radiant Cosmos",
"Choir Of Darkness",
"Girls Choir-Oh",
"Sound Cloud",
"Girls Choir-Staccato-Pa",
"Girls Choir-Morph Cloud",
"Girls Choir-Aa",
"Choir-Male-Oh",
"Angelic Host",
"Choir-Female-Oh",
"Ghosted",
"Crow Girls",
"Scanners",
"Disjointed",
"Chordal Vox",
"Drifting Choir",
"Epilogue",
"Only Twilight",
"Choir-Female-Oo",
"Girls Choir-Eh",
"Girls Choir Phrase Morph",
"Art Duo",
"Choir-Male-Eh",
"Choral Mist",
"Choir-Male-Ee",
"Girls Choir-Staccato-La",
"Celtic Fairy",
"Girls Choir-AyEeAhOh",
"Rotating Vowels",
"Floating Dreams",
"Girls Choir-Ee",
"Female Choir",
"Arcadia",
"LaLa Chorus",
"Call To Prayer",
"Girls Choir-Staccato-Aa",
"Amanda Ee-Aa Morph",
"Choir-Mixed-Ee",
"Girls Choir-Staccato-Ta",
"Lonely Dreams",
"Ah Breezes",
"Choir-Female-Mm",
"Girls Choir-Staccato-Oh",
"Mournful",
"Choir-Male-Mm",
"Bell Vox",
"Slavic Lands",
"Pagan Assembly",
"Anastacia Phrase Morphs",
"Art Shimmer",
"Girls Choir-Mm",
"Choir-Mixed-Mm",
"Girls Choir 02",
"Serpent Singers",
"Female Choir Morph",
"Intimate Weavers",
"Choir-Female-Ee",
"The Sad Choir",
"Girls Choir 01",
"Vocal Percussion",
"Byzantium Reeds",
"Short Vox Brass",
"Brass Section",
"Mountain Reeds",
"Trumpet Fusion",
"Jazz Club Trumpet",
"Water Jug Smack Bass",
"Crypt Bass",
"Bamboo Slurp",
"Analog Glide Lead",
"Water Creature Bass",
"Scrapyard Bass",
"Aquifer Blockage",
"Old Vinyl Piano Mallet",
"Industrial Fluids",
"Wow Bass",
"Disturbed Drone",
"Snapdragon",
"Echo Back Bass",
"Rainy Tape Bass",
"Finders Keepers",
"Liquid Glide Bass",
"Hypnotizing Lead",
"Power Drone",
"Tinkling Party Dress",
"Water Shredder",
"Liquid Buzz",
"Blacksmith",
"Jug Bass",
"Brawler",
"Iron Conqueror",
"Steam Reese",
"Deep Jab",
"Hydro Sub",
"Broken Pawnshop Guitar",
"Strange Geology",
"Jug Kalimba",
"Robotic Groove",
"Wishing Well",
"Contrapuntal",
"Grunge Rider",
"Clock Organ",
"Tribal House Atmosphere",
"Artificial Brain",
"Unstoppable Loop",
"Hold Me",
"Corroded Mechanism",
"Andromeda Probe",
"Stutter Mechanoid",
"Thumping Loop",
"Deep Air Patterns",
"Clockwork Grooves",
"Impact Suspense",
"Random Phrase",
"Steam Pressure",
"C64 Multiplexer",
"Hammer And Tongs",
"Traveller In Time",
"Techno Tock",
"Vocoder Jangle",
"Liquid Chaos",
"Spring Boing",
"Molecular Vibration",
"Water Gear",
"Awaking",
"At The Ruins",
"Messages From Space",
"Clockwork Guitar",
"Guitar Machine Chaos",
"Differential Red",
"Mud Flats",
"Bizarre Bits",
"Suspense",
"Sequential Acoustics",
"Marching Forward",
"Microscopic Wave Machine",
"Streaming Strummer",
"Impact Atmosphere",
"Sequential Acoustic Morphs",
"Beautiful Layered Lead",
"Buss Bar",
"Endless Strummer",
"Daylight Transformation",
"War Of The Drums",
"Coming Battle",
"Hawser Grunge",
"False Identity",
"Slow Space Drift",
"At the Beach",
"Water Comb",
"Whistle Birth",
"Atlantean Bells",
"Cirrus Clouds",
"Space Sentinel",
"Jupiter Red",
"90s Luscious Pad",
"Grey Worlds",
"Darkness Beyond",
"Winds Of Change",
"Simple Space",
"Siren Ensemble",
"High Tension",
"Cloud Chamber",
"Cistern Strings",
"Aquaponics",
"Through the Void",
"Space Walk",
"Ebb and Flow",
"Oculus Euchronia",
"Those Insects",
"Ocean Dawning",
"Moving Through Clouds",
"Beneath The Waves",
"The Retreat",
"Emerging From Ice",
"Positronic Consciousness",
"Glorious Sunrise",
"Sympathetic",
"Oceanic Gliss Pad",
"Vortex Distortion",
"Noisy Organic Pad",
"Oceanic Interference",
"Retrotronics",
"Steam Choir",
"Tesla Waves",
"Living History",
"The Cave",
"Rippling Chaos",
"Flickering Light Waves",
"Futuristic",
"Siren's Call",
"Fathers",
"Glassy Sheen Pad",
"Gliding Through Space",
"Luscious Ambient Patterns",
"Icarus",
"Sparse Beauty",
"Orbital Engines",
"Carrier Wave Goodbye",
"Fractal Wind",
"Aquatic Symphony",
"Abstracted Possibilities",
"Distant Ocean Pad",
"Artificial",
"Aquatic Undertow",
"Open Wormhole",
"Ashes Of Time",
"Klystron",
"Altruistic Deception",
"Ice Cutter",
"Catalyst",
"Mystic Stringed Pluck",
"The Wet Wall",
"Aqua Zither",
"Breath of Inspiration",
"Sharp Start Synth",
"Rainy Day Requiem",
"Chordal Perks",
"Glowing Synth Lead",
"Amphibian",
"Rainy Paradise",
"Swampy Lead",
"Watery Keys Falloff",
"Water Helicopter",
"Aqua Mallet",
"Thunder Line",
"Eastern Dream Vox",
"Piranha Echo Lead",
"Gliding Synth Lead",
"Restrained Lead",
"Wet Bar",
"Melodious Vowel Piano-Duo",
"Guitar Vox",
"Aquatic Resonator",
"Plastic Pizzicato",
"Synth String Section",
"Oil Can Keys",
"Rusty Water Contraption",
"Water Drop Sticks",
"Scarlett Bell",
"Bellophon",
"Warm Bell Pad",
"Metallic Bell Atmosphere",
"Woodblock Space",
"Watery Bells",
"Trembles",
"Filter Synth",
"Prismatic Bell",
"Raufarholshellir Crystals",
"Baroque",
"Echo Chimes",
"Dulcimer Wash",
"Caught In A Deep Thought",
"Gothic Bells",
"Balinese Dawn",
"Droplet Harp",
"Magic Lantern",
"Bendy Bowl",
"Pizzicato Wet Cave",
"Lonely Beacon",
"Chrysalis",
"Dreamy Bells",
"Clockwork Piano",
"Tuned Gongs",
"Mallet Sticks",
"Chiming Bells",
"Space Pan Flute",
"Flute Noise",
"Emerald River",
"Endless Didgeridoo 01",
"Endless Didgeridoo 03",
"Dream Flutes",
"Endless Didgeridoo 02",
"Flute Hold",
"Endless Didgeridoo 05",
"Flute Phonics",
"Endless Didgeridoo 04",
"Nightfall",
"Calliope Echoes",
"Sweet Flute Pad",
"Water Jug Clockwork",
"Pluck Me",
"Tin Piano",
"Servo-Assisted",
"Musical Box",
"Strings Of Distant Lands",
"Old Dreams",
"Aquatic Mallets",
"Raining Electric Piano",
"Sweet Bell",
"Reservoir Rhodes",
"Steampunk Piano",
"Groundwater",
"Ice Piano",
"Moon Water Keys",
"Water Keys",
"River Spray",
"Sun Setting in Bora Bora",
"Splashy Keys",
"Magical Box",
"Fractal Strum",
"Ice Water Keys",
"The Wonder",
"Watery Electric Piano",
"Dreamtime Pluck",
"Multi String Pluck",
"Transformed Guitar",
"Beyond Overdrive Lead",
"Struck Metal Drum",
"Hybrid Guitar Piano",
"Plucked Then Bowed Guitar",
"Harmonic Heaven",
"Ambient Guitar",
"Octave Strums",
"Black Overdrive",
"80s Dream Guitar",
"Chorus Shimmers",
"Mirror Guitar",
"Harmonies",
"Freshman Burns",
"Chorused Glisters",
"Dream and Mirage",
"Monet's Garden",
"Granular Tremolo Chorus",
"British Overdrive",
"Crystal Steel",
"Strange Stringed Thing",
"Reversed Guitar",
"Plucked Into Echoes",
"Distorted Tremolo",
"Oriental Nights",
"Cutie Pie",
"Another Time-Lapse",
"Chimes Of Our Life",
"Having A Splashing Time",
"The Rhythms",
"Secret Light",
"Rain on Windscreen",
"Meanwhile Motif",
"Staccato Arps",
"Arp Psychedelic Chord",
"Fast Bass Patterns",
"Fractal Chimes",
"Light Glider",
"Ehh Ihh Ahh Ohh",
"Power Chords",
"Analog Glide Arpeggiation",
"Rain In Heaven",
"Dowsing Rod",
"Acoustic Cascades",
"Arp Voyage",
"Happy Splashes",
"Shifting Pattern Machine",
"Gamelan Jam",
"Chained Mail",
"Antique Oriental",
"Seahorse",
"River Silk",
"Dancing Horses",
"Spring Splash",
"Destination",
"Distant Reflection",
"Tools Of Construction",
"Ha-Ha Vocals",
"Down The Road",
"Angle Of Elevation",
"Coal Scuttler",
"Ice Arps",
"Percussion Hit Loops",
"Deep and Groovy Overdrive",
"Split Personality",
"Square Bell Patterns",
"Ta Ta Arps",
"Dimension Vortex",
"Tight Punchy Lead",
"Anthemic Lead",
"Massive Glide Lead",
"High Energy Lead",
"Crackling Lead",
"Hard Metal Lead",
"Bending Lead",
"Mech Riser",
"Swirling Riser",
"Heavy Buzz Bass",
"Blooming Bass",
"Thick Liquid Bass",
"Talking Bass",
"Deep Thump Bass",
"Massive Wobble Bass",
"Sub Dropper",
"Rising Waves",
"7th Player",
"Future Strings",
"Classic Super Saw",
"Classic Choir",
"Les Inferno",
"Celestial Brass",
"Late Night Brass",
"80s Fantasy",
"Liquid Bass",
"Midnight Fuzz",
"Fever Nights",
"Layered Brass",
"Fireworks",
"Astro Funk",
"Thick Funk",
"Shining Lights",
"Floating Sensation",
"Solaris",
"Plucky Sine",
"Neon Dreams",
"Sparkling Stars",
"Instant Arcade",
"Vox Beats 12",
"Miner Kit",
"Dubstep Designer Kit 01",
"Drum Machine Kit",
"Hammer Kit",
"Tuned Cymbals",
"Slight Kit",
"Beat Box Battle Kit 11",
"Beat Box Battle Kit 05",
"Short Cut Kit",
"Cup Of Tea Kit",
"Synthetic Kit 02",
"Beat Box Battle Kit 04",
"Beat Box Battle Kit 10",
"Robotics Kit 01",
"Depth Kick",
"Robotics Kit 03",
"Beat Box Battle Kit 06",
"Beat Box Battle Kit 12",
"Synthesized Alchemy Kit",
"Synthetic Kit 01",
"Beat Box Battle Kit 13",
"Beat Box Battle Kit 07",
"Robotics Kit 02",
"Short Kit",
"Beat Box Battle Kit 03",
"Massive Hammer Kit",
"Beat Box Battle Kit 02",
"Hybrid Electronic Kit",
"Vox Kit 6",
"Beat Box Battle Kit 14",
"Beat Box Battle Kit 01",
"Vox Kit 7",
"Robotics Kit 04",
"Thai Tuned Gong",
"Tough Robot Kit",
"Filter Mod Kits",
"Dubstep Drum Set",
"Rough Cut Kit",
"Micro Kit",
"Beat Box Battle Kit 09",
"Weird Hollywood Drums",
"Crunch Kicks",
"Beat Box Battle Kit 08",
"Little Kit",
"Vox Kit 01",
"Hybrid Kit",
"Spiraling Chaos Kit",
"Raw Edge Kit",
"Dubstep FX Kit 01",
"Vox Kit 02",
"Dark Times Kit",
"Troll Drums",
"Vox Kit 03",
"Beat Box Parts 03",
"Beat Box Parts 02",
"Vox Impact Kit 01",
"Nimble Kit",
"Mega Click Kit",
"Vox Kit 04",
"Boom-Clap",
"Robotics FX Kit",
"Ragga Man Kit",
"Beat Box Parts 01",
"Vox Impact Kit 02",
"Neural Circuitry Remix Kit",
"Vox Kit 05",
"Hard PWM",
"Granular Amp Lead",
"Mechanical Glide Lead",
"Sync",
"Synth Guitar Overdrive",
"Drifting High Above",
"Punchy Gliding Synth Lead",
"Digiwave Lead",
"Tight Square Lead",
"Buzzy Saw Lead",
"Airhorn Anthem Lead",
"White Skies",
"Elastic Saw Lead",
"Bright Saw Anthem Lead",
"Bad Order",
"Red Delicious",
"Hubbard",
"Saw Wave Lead",
"Sizzling Glide Lead",
"Hardstyle Screech",
"Revenge",
"Boxy Glide Lead",
"Massive Festival Lead",
"Deep Sweep Lead",
"Drive-Saws",
"Otherworldly Vox Lead",
"Sick Trance",
"Screeching Lead",
"Grinding Synth Bass",
"Big Bright Lead",
"Screamer Lead",
"LoFi 80s Synth Lead",
"Space Square Lead",
"Clockwork Glide Lead",
"Huge Echo Lead",
"Psychic Projection Lead",
"Vintage Funk Space Lead",
"Square Dose",
"Party Power Lead",
"Midnight",
"Radical",
"Dub FX",
"Echo Percussion",
"Falling Plastic Stars",
"Bubbling Up",
"Sine Siren FX",
"Spiraling Out Of Control",
"Eight Alarms",
"Digital Rainfall",
"Uprising FX 01",
"Eerie Moment Generator",
"Noise Transition Stepped",
"Backwards Flurry",
"Aquatic Event",
"Moving Noise",
"Space Siren",
"Fall Down FX",
"Press Start Button",
"Baby Dropper",
"Fizzing Insects",
"Dark Overdrive Bass",
"Smudge",
"Splat Bass",
"Vox Bass FX Hits",
"Tardy Wobbler",
"Bold Bass",
"Pulse Variations",
"Dish Crusher",
"Short Nasty Bass",
"Bad Intentions",
"Growling Velocity Bass",
"House Bounce",
"Dragons Tail Sustain",
"Open Wide",
"Heavy Duty",
"Corrosion",
"Random Bass Pulsations",
"Deeper Geek",
"Wobble Saw",
"Unease Drone",
"Liquid Bass",
"Deep Noisy Bass",
"Hard Electro",
"Death Ray",
"Huge Overdrive Lead",
"Sharp Bass",
"Titanic Synth Bass",
"Terminal Termination",
"Backlash",
"Pocket Monster",
"Punchy Saw Bass",
"Grey Grain",
"Wobbly Bottom",
"Big Bass Wash",
"Simple Sine Bass",
"Tractor",
"Super Wide Fat Bass",
"Dubstep Wood",
"Boxy Resonant Bass",
"Dubstep Wobble 02",
"Vocalized Wobble",
"Deep Dark Funk Bass",
"Dub Solid Sub",
"Aggressor",
"Dark Wobble Bass",
"Alloy",
"Sub Dub Repeater",
"Dubstep Wobble 03",
"Vintage Fat Square Bass",
"Dense Distorted Bass",
"Grunge Bass",
"Time Bomb",
"Noisy Vox Bass",
"Big Buzz Bass",
"Dubstep Wobble 01",
"Heavily Distorted Lead",
"Heavy Funk Stack",
"Hex Throat",
"Sleepy Bear",
"Underwater Wobble Bass",
"Fuzzy Square Bass",
"Unison Saw Bass",
"Tumbler",
"Wobble Sub",
"Neural Corrosive",
"Mystic Cave Bass",
"Caterpillar",
"DnB Meets Hardstyle",
"Banjo Reformer",
"More Thumpers",
"Bouncing Bass",
"Strong Shot",
"Cutting Saw Bass",
"The Basics",
"Ring Mod Legato Bass",
"Shredded Bass Waves",
"Knocking Slide",
"Balloon Finger",
"Hard Dark Bass",
"Fizzy Square Bass",
"Massive Glide Bass",
"House My 5th",
"Resonant Wobble Patterns",
"Silver Tongued Synth",
"Solid Techno Bass",
"Super Sweep Synth",
"Sizzling Sine Bass",
"Fusion",
"Ultra Wide Saw Bass",
"Perimeter Alert",
"Nasty Wobble",
"Solid Snap Pluck",
"Rumble Bass",
"Vintage String Bass",
"Huge PWM",
"The Brick",
"Analog Bounce",
"Fast Saw Synth Lead",
"Deep Pulse Bass Synth",
"Simple Wobble Bass",
"Odd Paradigm",
"Tank",
"Queens Hall Wobbler",
"Boomerang Effect",
"Dragons Tail",
"Bulldozer",
"Solid Sequencer Bass",
"Squelch Bass",
"Swell",
"Club Bass",
"Crusty Phase",
"Noisy Synth Bass",
"Chopper",
"Dense Synth Chord",
"Slow Attack Bass",
"Liquid Pulsations",
"Wobble Bass Cycles",
"Dark Night",
"Warble Sword",
"For The Bottom",
"Quested Lime",
"On Spec",
"After The Snow",
"Zip Code",
"Dirty Wow Bass",
"DnB Sub Bass",
"Bouncing Echoes",
"My Mechanic",
"Balloon Kick",
"Slowly Moving Sub Bass",
"Dusty Old Synth Bass",
"Impossibly Huge Analog Bass",
"Rambunctious",
"Screaming Alchemist",
"Dark Antimatter",
"Rolling Square Bass",
"Kick Bass",
"Vox Upright Bass",
"Plastic Plate",
"Bass Machine Breakdown",
"Tight Swell Bass",
"Slab Of Sub",
"Dark Plastic",
"Big Boss",
"Muddy Pulsating Bass",
"Aggressive Synth Bass",
"Snowman Glasses",
"Silver Box Magic",
"Swirly Bass",
"Rubbery Synth Bass",
"Rich Octave Bass",
"Good Boy",
"Heavy Noisy Bass",
"Raw Stack",
"Layered Bass Stack",
"Thick Slow Sludge Bass",
"Fat Blue",
"JuneBugged",
"Space Organ Crater",
"Red Dust",
"Fat Stereo Add Bass",
"Dark Glide Lead",
"Dub Sub",
"Root Squared",
"70s Synth Lead Hero",
"Tube Drive Bass",
"Modern Wobble Bass",
"Deep Pluck Bass",
"Synth Double Bass",
"Combined Bass",
"Dirty Throb",
"Deep",
"Auto-Wobbler",
"Thumper",
"80s Hard Bass",
"No Use Crying",
"Restrained Bass",
"Rending Blast",
"Brassy Octave Bass",
"Glassy Wobble Bass",
"Chill Sustain",
"LoFi Bass Swirls",
"Ring Mod Solid Bass",
"Heavy Stacked Lead",
"Thumping Short Bass",
"Bug Bass",
"Wavetable Delayed",
"Wide And Modern",
"Dubstep Aerosol",
"Shifting Faces Of Bass",
"Heavy Dirty Bass",
"Massive Bass Overdrive",
"Sweeping Fuzz Bass",
"Minimal Subliminal",
"Ultra Sub Bass",
"Vox Synth Layers",
"Math Bass",
"Sneaky Bass",
"Insane Glory",
"Wub Wub Wub Wub",
"Flotation Device",
"Cluttered Synth Bass",
"Apprentice",
"Back Flash Bass",
"You Melt",
"Filth Wobbler",
"Sub-Bass Wobble",
"Digital Deep Bass",
"Garage Bass",
"Flappy Synth Bass",
"Chunky Vintage",
"Machine Code Wobble",
"In The Machine Bass",
"Dark Pluck",
"Bubbling Synth Bass",
"Dark Vintage Synth Bass",
"Dark Sweep Bass",
"Talking Bass Lead",
"Retro Wavetable Bass",
"Subculture",
"Dual Filtered Coffee",
"Heavy Tech House Bass",
"Europa Bass",
"Roaring Reese",
"Editor",
"Sub Trigger",
"Hip Bop",
"Rectangles",
"Deep Fried Junglist",
"Growl Bass",
"Vapor Bass",
"Triangle Tube Drive Bass",
"Insurgent",
"Alchemists Wavetable",
"House Attack",
"Slow Swirl Bass",
"Ghost Factory",
"Sustained Recluse",
"Vox Beats 06",
"Dramatic Moment Layers",
"Beat Box Loops 07",
"Plucky Synth Patterns",
"Shifting Echo Patterns",
"Indigenous Ritual",
"Deconstruction",
"Bass Noise Cycles",
"Bad Habit",
"Beat Box Loops 06",
"Cloud Cover",
"Insect Communication",
"Drum Beat Ghost",
"Vox Beats 07",
"Vox Beats 11",
"Vox Beats 05",
"Life in Slow Motion",
"Stephan Legacy",
"Neverending Machine",
"Beat Box Loops 04",
"Sweeping Resonant Patterns",
"Single Digit Acid Pattern",
"Single Digit Computer Song",
"Swelling Trance Riff",
"Beat Box Loops 05",
"Stick Rhythm Generator",
"Roughneck",
"Vox Beats 04",
"Vox Beats 10",
"Techno Groove 2",
"Rapidity",
"Beat Box Loops 01",
"Love That Tone",
"Weird Glitches",
"Re-grooving",
"Quad Saw Chord",
"Vox Beats and Bass 03",
"Vox Beats and Bass 02",
"Classic Electro Riff",
"Lonely Space Mod",
"Saw Sequence Bass",
"No Flange Beats",
"Sequenced Electro Hook",
"Private Groove",
"Vox Beats 01",
"Techno Groove 1",
"Beat Box Loops 02",
"Vox Beats and Bass 01",
"90s Dance Loop",
"Synced Auto Mod",
"Spring-Back",
"Beat Box Loops 03",
"Resonant Sequence",
"Speedy Squares",
"Strange Spaces Mod",
"Failing To Communicate",
"Vox Beats 02",
"Argentite",
"Ocean Smoke",
"Taking Flight",
"Notch Pulse",
"80s Chicago House Patterns",
"Flow Forms",
"Groove Maker 2",
"Midnight Pulse",
"Slap The Conga",
"Dreamy Bell Sequence",
"Pop Synth Echoes",
"Inevitable Gate",
"Rising Synth Waves",
"Bandura Phrases",
"Am I Funky",
"Off Beat Mod",
"Shake Me",
"Subdued Beast",
"Groove Maker 1",
"Quirky Synth Riff",
"Increasing Pulse",
"Rhythm Ghost 01",
"Vox Echoes",
"Basic Party Beat",
"Lyrical Chordal Patterns",
"Deep Ocean Ghost Pattern",
"Orchid Cargo",
"The Extra Android",
"Essential Pulse",
"Single Digit Choral Rhythm",
"Ferris Wheel",
"Rhythm Ghost 02",
"Sweet Mod",
"Driving Pulse",
"Old School",
"Primal Forces",
"Chaotic Beat Machine",
"Dusty Pulsations",
"Single Digit Vox Break 01",
"Auto Shuffle Pluck",
"Diminished Dream",
"Groove Keys",
"Melodic Bonk",
"Passing Through Tunnels",
"Metropolis",
"Night Sequence",
"Wave Dance",
"Flex Cream",
"Single Digit Vox Break 02",
"Digital Analog",
"Gated Chime Patterns",
"Single Digit Vox Break 03",
"Tribal House",
"Slider",
"Chopped Up",
"Cod War",
"Percussive 1",
"Adding",
"Syndrome",
"Sliced Approach",
"Single Digit Chords",
"Filter Cutter",
"Bit Drums",
"Metallic Hat Sequence",
"Brood",
"Percussive 2",
"Comb Pulse-Saw",
"Rough Edges",
"Dominance",
"Generic House",
"Moving Melody",
"Angular Mechanical Song",
"Interrupted",
"Busy Groove",
"Simple House Beat 02",
"Lunar Break",
"Ellis Dee Groove",
"Dark Tempo",
"Melodic Loop Mashup",
"Swirling Techno Beat",
"March of the Frogs",
"Electronic Puncher",
"Mental Sequence 140 BPM+",
"Tribal House Loop",
"Flex Chopper",
"Joyous",
"Simple House Beat 01",
"Night Spike",
"Distant Clap Space",
"Blister",
"Fat Synth Rhythm",
"Vox Beats 09",
"Lunar Landing",
"Hard Hitting Beat",
"Kick Cycles 02",
"Vital Signs",
"Ingenuity",
"Phasing Dreams",
"Electron Rush",
"Donnie Mod",
"Fire Eater Patterns",
"Vox Beats 08",
"Blue Miter",
"Kick Cycles 01",
"Later Gator",
"Harsh One",
"Northern Winds",
"Vintage Analog",
"Phaser Pad",
"State of Grace",
"Angel Pad",
"Anthem Pad",
"Transmitter",
"Night Culture",
"Butterfly Effect",
"Low Earth Orbit",
"Charm",
"Classic House Stack 02",
"Classic House Stack 03",
"Classic House Stack 01",
"Concussion",
"Fire Fly",
"Passage",
"Purple Sun",
"Sparkling Techno Lead",
"Fuzzy Poly Synth",
"Limbo",
"Sunlight On Water",
"Breathy Exhale",
"Dream State",
"Dance Chord",
"Retrograde",
"Primal",
"Short Pulse",
"Mud Morphing",
"Journey",
"Warped Phase",
"Short Metallic Echoes",
"Slam Sweeper",
"Feather Brass",
"Epic And Punchy",
"Deep Techno Chords 02",
"Hollow Scream",
"Square Piano",
"Deep Techno Chords 01",
"Perseverance",
"Noisy Wobbled Saw",
"Tubular Synth Bells",
"Vox Sweep Release",
"Console",
"Massive Saw Patterns",
"Computer Music 1977",
"Pulsing Bottles",
"Jumping Waves",
"Dreams Illuminated",
"Trance Chord",
"Off Road",
"Minimalist Paradox",
"Lush Saw Patterns",
"Strange Clockwork",
"Brilliant Synth Patterns",
"Future Never Waits",
"Trance Movement",
"Thruster",
"Sweet Gated Layers",
"Crystal Cascades",
"Warm Pad Patterns",
"Serpentine",
"House Stabs",
"Chimer",
"Synth Guitar Arps",
"Dark Synth Wave",
"Counting Cards in Vegas",
"Huge Virus Bells",
"Heavy Resonant Machine",
"Two Filter Sequencer",
"Ancient Titan",
"Mellow Synth Patterns",
"Gliding Squares",
"Double Note Morph",
"Analog Head-Nod",
"Cascading Bells",
"Contrary Motion",
"Resonant Acid Patterns",
"Single Digit Pulse Pattern",
"Gated Pad Patterns",
"Electro House Pattern",
"Soft Ambient Arps",
"Shifting Metallic Patterns",
"Square Pluck",
"Tunnel Driving Arpeggiator",
"Breathy Pop Patterns",
"International Mystery",
"Single Digit Movement",
"Skywriter",
"Log Jam",
"Swinging Saw Arp",
"Kilobyte",
"Tin Man",
"Retroactive",
"Cave Dripping",
"Super Soft",
"After Image Echoes",
"Single Digit Suspense",
"Random Triples",
"Solid Twangs",
"Hi-Bells",
"Dance Ticks",
"Echo Percussion Patterns",
"Wash And Spin",
"Trance Runner",
"1970s Modular Synth Bass",
"Moving Saw Patterns",
"Cascades",
"Arpeggiated Echo Drums",
"Club Heads",
"Noise Pad Layers",
"Freeway",
"Divers In The Azure Blue",
"Dream Chord",
"Space Bass Patterns",
"Pots And Pans",
"Sweeping Layers",
"Gated Monster",
"Saw Wave Patterns",
"Mechanic",
"Syncopated Dance Chord",
"Single Digit Anthem",
"Acid Trance Pattern",
"Paper Thin Drama",
"Bass Echo Patterns",
"Driving Tube Patterns",
"Aquatic Ghosts",
"Space Duck",
"70s Space Synth Patterns",
"Deep Electro Bass Patterns",
"Classic Bass Arp",
"Darker Forest",
"80s Simple Synth Patterns",
"Sparkle",
"Anthemic Arpeggiation",
"Chip",
"Jack Hammer",
"Pulsating Squares",
"Slip And Slide Sequence",
"Little Pieces",
"Mission to Saturn",
"Star Bugs",
"Falling Leaves",
"This Is Nu Goa",
"Dark Deep Pulsations",
"Single Digit Bass Sequence",
"Rusty Automaton",
"Tribe",
"Worker Bee",
"Rain Drops Fluttering",
"Fluid Motions",
"Ghost Chord Patterns",
"Deep Space Borealis",
"Spooky Bell Sequence",
"Calming Mantra",
"Cathedral Fugue",
"Galloping Cascades",
"Tight Arp Patterns",
"Modern Trance Pluck",
"Guitar Chord Funk",
"Slow Winding Acid Loop",
"Mega Trance",
"Songhellir Cave Kit",
"Tight Vox Kit",
"Machine Kit",
"Small Kit",
"Breakbeat Kit Granular",
"Tiny Kit",
"Light Space Organic Kit",
"Nano Kit",
"Thin Kit",
"EllyAnna Germ Kit",
"Compact Kit",
"Amanda Mouth Percussion Kit",
"60s Vintage Organ",
"VA Church Organ",
"Dirt Organ",
"Chill Organ",
"Glowing Tones",
"Nouveaux 60s Organ",
"Vintage Vox Organ",
"Small Classic Organ",
"Organ Harmonia",
"Godsender",
"Quirky Organ Stack",
"Organ Bass Space",
"Additive Church Organ",
"Primitive Synth Organ",
"Monster Pick Bass",
"Rubber Bass",
"Electric Upright",
"Electric Upright Short",
"Downtempo Electric Bass",
"Room Pluck",
"Bass So Full",
"Jazz Session Bass",
"Nasty Bass Suspense",
"Cheap Upright Bass",
"Slap Back",
"Semi-Acoustic Human",
"1963 Semi-Acoustic Thumb",
"Clean 70s Synth Bass",
"Upright Bass Sustain",
"Battered Bass",
"Blown Woofer Bass",
"Dirty Filthy Electric Bass",
"Hard Semi Acoustic",
"Electric Upright Sustain",
"Semi-Acoustic Short",
"Friendly Fire",
"Upright Bass Collection",
"Semi-Acoustic Doubled",
"Rounded",
"Magma",
"Floating",
"Shifting Gating Pads",
"Freezing Wind Bells",
"Autumn Wings",
"Swelling Flutter Pad 03",
"Swelling Flutter Pad 02",
"Swelling Flutter Pad 01",
"Slow Departure",
"Deep Summer Twilight",
"Deep Pulsating River",
"Morphing Ring Mod Pad",
"Icy Winds",
"Blue Through the Porthole",
"Swirling Stars",
"Simple Dreamy Synth",
"Shimmering Release",
"Gently Sweeping Pads",
"Alien Harp",
"8 Light Years From Here",
"Wavetable Sweeps",
"Majestic Space Synth",
"Ethereal Pluck",
"Thin and Meek",
"Poly-Squelch",
"Harpsichord Synth",
"Ukulele Echoes",
"Glorious Gliss",
"Rich Stereo Synth Keys",
"Chillwave Vibes",
"Sign of Life",
"Small Chirping Synth",
"Gliss Keys Granular",
"Crisp and Shiny",
"Dense Brass",
"Black Velvet Curtain",
"Hopeful Synth",
"New Asia",
"Gently Phasing Squares",
"Dirty Swirling Synth",
"Soft Sync Staccato",
"Notched Squares",
"Glimmering Noise",
"Brittle",
"Feedback Cut",
"Spacey Dream Bell",
"Smoky Bells",
"Titanic Pluck",
"Dark Mallet Echoes",
"Hold",
"Long Mel",
"Noise Note",
"Small Echoing Plucks",
"Landscaping",
"Strange Dreams",
"Stereo Wavetable Synth",
"Wavetable Organ",
"Glitch Mallet",
"Clean Cool Vibes",
"FM Mallet Echoes",
"Light Mallet Echo Layers",
"Hybrid Kalimba Vibraphone",
"Frozen Bells",
"Murmuring Bells",
"Light Bulbs",
"Dense Metallic Tines",
"Fantasia Frets",
"Sunbeams",
"Lazy Vibes",
"Grand Pluck",
"Fragile Thoughts",
"Fuzzy Logic Piano",
"Wavy Analog Synth Piano",
"Mellotron Choir",
"Flexi Suitcase",
"Abstract Electric Piano",
"Hidden Voices",
"Analog Harpsichord",
"Completely VA Suitcase",
"Music Box",
"80s Glassy Electric Piano",
"Bell Keys",
"Bell Layers",
"Analog EP",
"Wooden Bells",
"Light Synth Brass",
"80s Pop Electric Piano",
"Sparkling Necklace",
"Bird Song",
"Ships Piano",
"The Far East",
"Harpsichord-Mute",
"Glassy Bell Pad",
"Electric Piano Bells",
"Harpsichord-Open",
"Fizzy Bell Keys",
"Vox Keys",
"Electric Piano Vox Layers",
"Fizzy Funk Synth",
"VA Chime Piano",
"Vox Kit 8",
"Bell Like Vox Vibes",
"Mallet-O-Harmonics",
"Autoharp-Binaural",
"Bottle Bells",
"Naive Bells V",
"FM Dark Electric Piano",
"Primitive Analog Female Vox",
"80s Digital Piano",
"Spacy E-Piano",
"Dirty House Organ",
"Shadow Keyboard",
"Baroque Harpsichord",
"Electro Funk Clav",
"Automata",
"Four Walls",
"FM Light Electric Piano",
"80s Bell Vox Layers",
"Dark and Funky EP",
"Lemon Fields",
"Funky Nasal Clavinet",
"Pizzicato Echoes",
"Vox Deow",
"Old Harpsichord",
"Stringed Sparklers",
"Old Time Radio",
"Strange Plucky Guitar",
"12 String Split",
"Post Rock Guitar",
"Small Pluck Echoes",
"Strange Guitar Space",
"Sonicus",
"Acoustic Pluck",
"Hither and Zither",
"Tone Bender",
"Dulcimer Reverser",
"Pluck Layer",
"Guitar PM Acoustic",
"Mood Acoustic",
"Gentle Quirks",
"Lost Temple",
"Silver Ballad",
"Bandura Dreams",
"Ethereal Guitar",
"Bandura Unison",
"Drifting Guitar Riff",
"Mosaic Guitar",
"12 Strings",
"Electric Eighties",
"Middle Eastern Dreams",
"Magic Hat",
"Autumn Legends",
"Fast Tremolo Guitar",
"Granular Magnetic Guitar",
];